# Generated by Django 3.2 on 2021-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('last_tech_inspection', models.DateTimeField()),
            ],
        ),
    ]
