# Generated by Django 3.2 on 2021-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210427_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='program',
            field=models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], max_length=20, null=True),
        ),
    ]
